name: 'Basic Test Results'
description: 'Aggregates and processes tests files in CI. Outputs the failed tests as a comment on the PR.'
inputs:
  github-token:
    description: |
      'The secrets.GITHUB_TOKEN to be able to interact with the current PR and comment on it.'
    required: true
  test-file-regex:
    description: |
      'The regex for the junit file that we want to run the test-processor for.'
    default: '*junit.xml'
    required: true
  directory:
    description: |
      'Directory to download all the junit artifacts that match the test-file-regex. If not specified, then it will be test_results.'
    required: true
    default: 'test_results'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Codecov CLI
      run: pip install codecov-cli==0.7.6
      shell: bash

    - name: Run Test Results Processor
      if: ${{ !cancelled() }}
      shell: bash
      env:
        TEST_DIR: ${{ inputs.directory }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        codecovcli process-test-results --dir ${TEST_DIR} --github-token ${GITHUB_TOKEN}
