name: Test on multiple platforms
on:
  pull_request: 
  push:
    branches:
      - main
jobs:
  collect-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
        OS: ${{ matrix.os }}
        PYTHON: '3.10'
    steps:
      - uses: actions/checkout@master
      - name: Upload custom test
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}junit.xml
          path: demo/calculator/junit.xml
      - name: Run Basic Test Results Action, Verify OS
        uses: ./
        with:
          directory: demo/calculator/
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  run-test-on-file:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
        OS: ${{ matrix.os }}
        PYTHON: '3.10'
    steps:
      - uses: actions/checkout@master
      - name: Run Basic Test Results Action, Specify file with Disabled Search
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: demo/calculator/junit.xml
          disable-search: true

  parse-tests:
    runs-on: ubuntu-latest
    needs: [collect-tests]
    steps:
      - uses: actions/checkout@master
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: '*junit.xml'
          path: 'test_results'
          merge-multiple: true
      - name: Run Basic Test Results Action, Compile All, verbose
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: 'test_results'