name: Test on multiple platforms
on:
  pull_request: 
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
        OS: ${{ matrix.os }}
        PYTHON: '3.10'
    steps:
      - uses: actions/checkout@master
      - name: Run Basic Test Results Action
        uses: ./
        with:
          directory: demo/calculator/
          github-token: ${{ secrets.GITHUB_TOKEN }}
